import os
from dotenv import load_dotenv

load_dotenv()
INQUISITOR_TOKEN = os.getenv('INQUISITOR_TOKEN')
GLAUCON_TOKEN = os.getenv('GLAUCON_TOKEN')
ASE_TOKEN = os.getenv('ASE_TOKEN')
INSIDE_TRACK_TOKEN = os.getenv('INSIDE_TRACK_TOKEN')
DMERSHON_TEST_GUILD = os.getenv('DMERSHON_TEST_GUILD')
FLAUSTRIA_GUILD = os.getenv('FLAUSTRIA_GUILD')
FIREBASE = os.getenv('FIREBASE_TOKEN')
TWITTER_CONSUMER_KEY = os.getenv('TWITTER_CONSUMER_KEY')
TWITTER_CONSUMER_SECRET = os.getenv('TWITTER_CONSUMER_SECRET')
TWITTER_ACCESS_TOKEN = os.getenv('TWITTER_ACCESS_TOKEN')
TWITTER_ACCESS_TOKEN_SECRET = os.getenv('TWITTER_ACCESS_TOKEN_SECRET')
